theme: minima
title: Books to Behold
author: Phorys
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Well, the title says it all...

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Phorys # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
